keycloak:
  server-url: http://localhost:8081
  realms:
    user-application:
      name: user-application
      client-id: user-manager
      client-secret: xgntDDfJiuaPc1XaSHuQgEO7KoffiBHA
      grant-type: client_credentials